# Production environment override
services:
  app:
    build:
      context: ./docker/php
      target: php_prod
      args:
        APP_PORT: ${APP_PORT}
        TIMEZONE: ${TIMEZONE}
        UID: ${UID}
        GID: ${GID}

  supervisor:
    build:
      context: ./docker/php
      target: php_prod_supervisor
      args:
        APP_PORT: ${APP_PORT}
        TIMEZONE: ${TIMEZONE}
        UID: ${UID}
        GID: ${GID}

  nginx:
    build:
      context: ./docker/nginx
      args:
        UID: ${UID}
        GID: ${GID}

  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      target: node_prod
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports: []
